# Generated by Django 4.1.7 on 2023-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="アイコン"
            ),
        ),
    ]
