# Generated by Django 4.1.7 on 2023-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="締切日時"),
        ),
    ]
