# Generated by Django 4.1.7 on 2023-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="完了済"
            ),
        ),
    ]
